### ISSUE TITLE
If default=False  the default value isn't sent

### ISSUE THREAD

**Issue by desean1625** [spectriclabs/envappconfig#1]
Unable to set default value to False
```
env.add_env("PROD",default=False,transform=lambda x: x.lower() != 'false',help="by default will run app in dev mode")
```
@ballenspectric should be able to just check if default is not None
https://github.com/spectriclabs/envappconfig/blob/938f50aa5246ac0ccbc5923402373cac97f7a5d5/envappconfig/envappconfig.py#L42

**Comment by ballenspectric** [comment]
Fixed in version 2023.198.827.
